-- PostgreSQL Schema for Clubora Sports Club Management System
-- Database Name: Clubora

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'FRONT_DESK',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS membership_tiers (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  monthly_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  court_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  shop_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  bar_discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  description TEXT
);

CREATE TABLE IF NOT EXISTS members (
  id VARCHAR(36) PRIMARY KEY,
  member_code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(50),
  tier_id VARCHAR(36) NOT NULL REFERENCES membership_tiers(id) ON DELETE RESTRICT,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(50) DEFAULT 'ACTIVE',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courts (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  sport VARCHAR(50) NOT NULL,
  hourly_rate NUMERIC(10,2) NOT NULL,
  is_available BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS bookings (
  id VARCHAR(36) PRIMARY KEY,
  court_id VARCHAR(36) NOT NULL REFERENCES courts(id) ON DELETE RESTRICT,
  member_id VARCHAR(36) REFERENCES members(id) ON DELETE SET NULL,
  customer_name VARCHAR(255) NOT NULL,
  booking_date VARCHAR(20) NOT NULL,
  start_time VARCHAR(10) NOT NULL,
  end_time VARCHAR(10) NOT NULL,
  is_social_play BOOLEAN DEFAULT FALSE,
  players_count INTEGER DEFAULT 1,
  original_fee NUMERIC(10,2) NOT NULL,
  discount_fee NUMERIC(10,2) NOT NULL,
  final_fee NUMERIC(10,2) NOT NULL,
  payment_status VARCHAR(50) DEFAULT 'PAID',
  status VARCHAR(50) DEFAULT 'CONFIRMED',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  stock_quantity INTEGER NOT NULL,
  low_stock_threshold INTEGER DEFAULT 5,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_requests (
  id VARCHAR(36) PRIMARY KEY,
  product_id VARCHAR(36) REFERENCES products(id) ON DELETE SET NULL,
  item_name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'ACCESSORIES',
  requested_quantity INTEGER NOT NULL CHECK (requested_quantity > 0),
  received_quantity INTEGER NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  requested_by VARCHAR(255) NOT NULL,
  requested_by_role VARCHAR(50) DEFAULT 'BAR_SHOP_STAFF',
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  notes TEXT,
  approved_by VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id VARCHAR(36) PRIMARY KEY,
  product_id VARCHAR(36) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  total_price NUMERIC(10,2) NOT NULL,
  channel VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bar_items (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  is_available BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS bar_tabs (
  id VARCHAR(36) PRIMARY KEY,
  tab_number VARCHAR(50) UNIQUE NOT NULL,
  member_id VARCHAR(36) REFERENCES members(id) ON DELETE SET NULL,
  customer_name VARCHAR(255) NOT NULL,
  table_number VARCHAR(50),
  status VARCHAR(50) DEFAULT 'OPEN',
  total_amount NUMERIC(10,2) DEFAULT 0.00,
  discount_percent NUMERIC(5,2) DEFAULT 0.00,
  discount_amount NUMERIC(10,2) DEFAULT 0.00,
  final_amount NUMERIC(10,2) DEFAULT 0.00,
  payment_method VARCHAR(50),
  opened_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  settled_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS bar_order_items (
  id VARCHAR(36) PRIMARY KEY,
  tab_id VARCHAR(36) NOT NULL REFERENCES bar_tabs(id) ON DELETE CASCADE,
  bar_item_id VARCHAR(36) NOT NULL REFERENCES bar_items(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  total_price NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS leads (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  interest VARCHAR(255) NOT NULL,
  status VARCHAR(50) DEFAULT 'NEW',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
  id VARCHAR(36) PRIMARY KEY,
  lead_id VARCHAR(36) NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  tier_name VARCHAR(100) NOT NULL,
  court_hours INTEGER DEFAULT 0,
  total_price NUMERIC(10,2) NOT NULL,
  valid_until VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'SENT',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shifts (
  id VARCHAR(36) PRIMARY KEY,
  staff_name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  date VARCHAR(20) NOT NULL,
  start_time VARCHAR(10) NOT NULL,
  end_time VARCHAR(10) NOT NULL,
  status VARCHAR(50) DEFAULT 'SCHEDULED'
);

CREATE TABLE IF NOT EXISTS invoices (
  id VARCHAR(36) PRIMARY KEY,
  invoice_number VARCHAR(50) UNIQUE NOT NULL,
  client_name VARCHAR(255) NOT NULL,
  client_email VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  due_date VARCHAR(20) NOT NULL,
  status VARCHAR(50) DEFAULT 'PENDING',
  paid_at TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Migration: ensure notes column exists (may be missing if table was created before schema update)
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS leave_requests (
  id VARCHAR(36) PRIMARY KEY,
  staff_name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  leave_type VARCHAR(50) NOT NULL DEFAULT 'CASUAL',
  start_date VARCHAR(20) NOT NULL,
  end_date VARCHAR(20) NOT NULL,
  reason TEXT,
  status VARCHAR(50) DEFAULT 'PENDING',
  reviewed_by VARCHAR(255),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS bar_expenses CASCADE;

CREATE TABLE IF NOT EXISTS bar_expenses (
  id VARCHAR(36) PRIMARY KEY,
  expense_date VARCHAR(20) NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) DEFAULT 'Inventory',
  amount NUMERIC(10,2) NOT NULL,
  notes TEXT,
  created_by VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bar_expenses_date ON bar_expenses(expense_date);

CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);
CREATE INDEX IF NOT EXISTS idx_members_tier_id ON members(tier_id);
CREATE INDEX IF NOT EXISTS idx_bookings_court_date ON bookings(court_id, booking_date);
CREATE INDEX IF NOT EXISTS idx_bar_tabs_status ON bar_tabs(status);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_shifts_date ON shifts(date);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON leave_requests(status);

CREATE TABLE IF NOT EXISTS payments (
  id VARCHAR(36) PRIMARY KEY,
  booking_id VARCHAR(36) REFERENCES bookings(id) ON DELETE CASCADE,
  amount NUMERIC(10,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'INR',
  method VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  razorpay_order_id VARCHAR(255),
  razorpay_payment_id VARCHAR(255),
  razorpay_signature VARCHAR(255),
  error_code VARCHAR(255),
  error_description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payments_booking_id ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_razorpay_order_id ON payments(razorpay_order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

